#!/usr/bin/python3
"""
Module that provides function for determining if all
boxes in given list can be opened.
"""


def canUnlockAll(boxes):
    """
        This function takes list of lists and returns boolean indicating
        whether all boxes in list can be opened. A key with same
        number as box opens that box. You can assume all b_keys will be
        positive integers. 
        There can be b_keys that do not have boxes.
        First box boxes[0] is unlocked.
    """
    if (type(boxes) is not list):
        return False

    if (len(boxes) == 0):
        return False

    b_keys = [0]
    for x in b_keys:
        for y in boxes[x]:
            if y not in b_keys and y != x and y < len(boxes) and y != 0:
                b_keys.append(y)
    if len(b_keys) == len(boxes):
        return True
    else:
        return False
